name: Build PDF from Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: pandoc -s PRD.md -o PRD.pdf

    - name: Upload PDF to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PRD-pdf
        path: PRD.pdf
