name: Convert PRD to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'docs/PRD.md'

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          images_dir: docs/images # Update this if you have images in your Markdown
          image_import: ./images   # Ensure this path is correct based on your Markdown image links
          build_html: false        # Set this to true if you also need HTML output

      - name: Upload PDF to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs
